from zuikuihuoshou.parser.image.bmp import BmpFile  # noqa
from zuikuihuoshou.parser.image.gif import GifFile  # noqa
from zuikuihuoshou.parser.image.ico import IcoFile  # noqa
from zuikuihuoshou.parser.image.jpeg import JpegFile  # noqa
from zuikuihuoshou.parser.image.pcx import PcxFile  # noqa
from zuikuihuoshou.parser.image.psd import PsdFile  # noqa
from zuikuihuoshou.parser.image.png import PngFile  # noqa
from zuikuihuoshou.parser.image.tga import TargaFile  # noqa
from zuikuihuoshou.parser.image.tiff import TiffFile  # noqa
from zuikuihuoshou.parser.image.wmf import WMF_File  # noqa
from zuikuihuoshou.parser.image.xcf import XcfFile  # noqa
from zuikuihuoshou.parser.image.cr2 import CR2File  # noqa
